### ISSUE TITLE
[MTT] Fail in osu_put_bibw

### ISSUE THREAD

**Issue by avildema** [openucx/ucc#284] opened 2021-08-03 10:45 UTC
Configuration
```
OMPI: v5.0.0a1
MOFED: MLNX_OFED_LINUX-5.4-1.0.3.0
Module: none
Test module: none
Nodes: jazz x12 (ppn=28(x12), nodelist=jazz[12-21,29-30])
```
 
MTT log:
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucc/20210802_170250_189628_54877_jazz12.swx.labs.mlnx/html/test_stdout_Ccnq4w.txt
 
Cmd:
`/hpc/mtr_scrap/users/mtt/scratch/ucc/20210802_170250_189628_54877_jazz12.swx.labs.mlnx/ompi_src/install/bin/mpirun -np 2 --display map --mca coll_ucc_enable 1 --mca coll_ucc_priority 100 -x UCC_TL_UCP_TUNE=allreduce:1 --map-by node --bind-to core /hpc/mtr_scrap/users/mtt/scratch/ucc/20210802_170250_189628_54877_jazz12.swx.labs.mlnx/installs/OSS4/tests/osu_micro_benchmark/osu-micro-benchmarks-5.6.2/mpi/one-sided/osu_put_bibw`
 
Output:
```sh
# OSU MPI_Put Bi-directional Bandwidth Test v5.6.2
# Window creation: MPI_Win_allocate
# Synchronization: MPI_Win_post/start/complete/wait
# Size      Bandwidth (MB/s)[jazz13.swx.labs.mlnx:163928] ../../../../opal/mca/common/ucx/common_ucx_wpool.h:526  Error: ucp_atomic_cswap64 failed: -1
[jazz13:00000] *** An error occurred in MPI_Win_post
[jazz13:00000] *** reported by process [1362690049,1]
[jazz13:00000] *** on win ucx window 3
[jazz13:00000] *** MPI_ERR_OTHER: known error not in list
[jazz13:00000] *** MPI_ERRORS_ARE_FATAL (processes in this win will now abort,
[jazz13:00000] ***    and MPI will try to terminate your MPI job as well)+ rc=16
```

**Comment by vspetrov** [comment] 2021-08-06 06:50
@avildema i've closed such ticket couple of days back. Now it is reopened again. Why is it reported to UCC? It is bibw test that does not run collectives? The failure happens in ompi/ucx. Does it work w/o ucc?

**Comment by avildema** [comment] 2021-08-06 07:00
Yes, happen only in ucc+ompi test, w/o ucc test is OK

**Comment by lappazos** [comment] 2021-08-18 13:02
I spoke with @avildema, looks like it is indeed not related to UCC. when using OMPI master, without UCC at all, bug still reproduced.
@avildema please verify me that the bug is happening even without UCC, and then we can close this issue. Let me know if you need me to report this bug to OMPI. Thanks

**Comment by avildema** [comment] 2021-08-18 13:26
@lappazos  Yes, please report this bug to OMPI

**Closed** 2021-08-31 13:10 UTC
Labels: mtt
